version: "3.7"

services:
    django:
        networks:
            - nginx-proxy
        container_name: boilerplate
        hostname: boilerplate.e-lms.cl
        build: 
            context: ../
            dockerfile: .docker/app/Dockerfile
            target: production
            args:
                UID: 1001
                GID: 100
        command: gunicorn --workers=2 --threads=4 --worker-class=gthread --worker-tmp-dir /dev/shm --bind :8000 core.wsgi
        volumes:
            - /home/instalar/static/boilerplate/:/static/:rw
            - /home/instalar/media/boilerplate/:/media/:rw
            - /home/instalar/logs/boilerplate:/logs:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        expose:
            - 8000
        env_file:
            - app/.env
        restart: always

networks:
    nginx-proxy:
      external: true
      name: nginx-proxy