version: "3.9"

services:
    postgresql:
        image: postgres:13.3
        expose:
            - 5432
        restart: on-failure
        volumes:
            - ./data/postgres/:/var/lib/postgresql:rw
        environment: 
            POSTGRES_USER: desarrollo
            POSTGRES_PASSWORD: desarroll0
            POSTGRES_DB: boilerplate
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U desarrollo -d boilerplate"]
            interval: 10s
            timeout: 5s
            retries: 5
    django:
        container_name: boilerplate
        build: 
            context: ../
            dockerfile: .docker/app/Dockerfile
            target: develop
            args:
                UID: 1001
                GID: 100
        command: python manage.py runserver 0.0.0.0:8000 --settings=core.settings.docker
        restart: always
        volumes:
            - ../app/:/home/instalar/app/:rw
            - ../app/_media/:/media/:rw
            - ../app/staticfiles/:/static/:rw
        ports: 
            - 8000:8000
        env_file: ./app/.env
        depends_on:
            postgresql:
                condition: service_healthy